# x1yoga configuration - Lenovo ThinkPad X1 Yoga Gen 6
{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ../../modules/boot/limine-plymouth.nix
    ../../modules/hardware/intel.nix
  ];

  networking.hostName = "x1yoga";

  # === Intel Tiger Lake (11th Gen) GPU Configuration ===
  # Intel Iris Xe Graphics - uses i915 kernel module
  # Early KMS is handled by intel.nix module

  # Early boot kernel modules (order matters for proper initialization)
  # - GPU modules first: enables early KMS for high-res Plymouth/console
  # - HID modules: ensures keyboard works for LUKS passphrase entry
  boot.initrd.kernelModules = lib.mkForce [
    "i915"         # GPU: early KMS for Plymouth and console
    "hid-generic"  # Input: generic HID driver for keyboards
    "usbhid"       # Input: USB HID for external keyboards
  ];

  # ThinkPad-specific power management
  services.tlp = {
    enable = true;
    settings = {
      # CPU scaling
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
      CPU_ENERGY_PERF_POLICY_ON_AC = "performance";
      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";

      # Intel GPU power management
      INTEL_GPU_MIN_FREQ_ON_AC = 350;
      INTEL_GPU_MIN_FREQ_ON_BAT = 350;
      INTEL_GPU_MAX_FREQ_ON_AC = 1300;
      INTEL_GPU_MAX_FREQ_ON_BAT = 800;

      # ThinkPad battery thresholds (extend battery lifespan)
      START_CHARGE_THRESH_BAT0 = 75;
      STOP_CHARGE_THRESH_BAT0 = 80;
    };
  };

  # Disable power-profiles-daemon (conflicts with TLP)
  services.power-profiles-daemon.enable = false;

  # Firmware updates via fwupd (ThinkPads are well supported)
  services.fwupd.enable = true;

  # Touchscreen and stylus support
  services.libinput.enable = true;

  # Fingerprint reader support (Synaptics Prometheus)
  services.fprintd.enable = true;

  # PAM fingerprint authentication
  security.pam.services = {
    login.fprintAuth = true;          # Console login
    greetd.fprintAuth = true;         # Display manager
    sudo.fprintAuth = true;           # Sudo commands
    polkit-1.fprintAuth = true;       # Polkit prompts (1Password, etc.)
    hyprlock.fprintAuth = true;       # Screen lock
  };

  # ThinkPad ACPI extras (fan control, special keys)
  boot.kernelModules = [ "thinkpad_acpi" ];
  boot.extraModprobeConfig = ''
    options thinkpad_acpi fan_control=1
  '';

  # LUKS configuration is handled by disko (modules/disko/x1yoga.nix)
  # Disko sets allowDiscards and bypassWorkqueues automatically

  # Hibernate support (auto-generated by Forge installer)
  boot.resumeDevice = "/dev/mapper/cryptroot";
  boot.kernelParams = [
    "resume_offset=533760"
    "i915.enable_psr=0"  # Disable Panel Self Refresh - suspected cause of random crashes
  ];
  zramSwap.enable = lib.mkForce false;

}
