# xps9320 configuration - Dell XPS 13 9320
{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ../../modules/boot/limine-plymouth.nix
    ../../modules/hardware/intel.nix
  ];

  networking.hostName = "xps9320";

  # === Intel Alder Lake (12th Gen) GPU Configuration ===
  # Intel Iris Xe Graphics - uses i915 kernel module
  # Early KMS is handled by intel.nix module

  # Early boot kernel modules (order matters for proper initialization)
  # - GPU modules first: enables early KMS for high-res Plymouth/console
  # - HID modules: ensures keyboard works for LUKS passphrase entry
  boot.initrd.kernelModules = lib.mkForce [
    "i915"         # GPU: early KMS for Plymouth and console
    "hid-generic"  # Input: generic HID driver for keyboards
    "usbhid"       # Input: USB HID for external keyboards
  ];

  # Dell XPS power management
  services.tlp = {
    enable = true;
    settings = {
      # CPU scaling
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";
      CPU_ENERGY_PERF_POLICY_ON_AC = "performance";
      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";

      # Intel GPU power management
      INTEL_GPU_MIN_FREQ_ON_AC = 300;
      INTEL_GPU_MIN_FREQ_ON_BAT = 300;
      INTEL_GPU_MAX_FREQ_ON_AC = 1300;
      INTEL_GPU_MAX_FREQ_ON_BAT = 800;

      # Dell battery thresholds (extend battery lifespan)
      START_CHARGE_THRESH_BAT0 = 75;
      STOP_CHARGE_THRESH_BAT0 = 80;
    };
  };

  # Disable power-profiles-daemon (conflicts with TLP)
  services.power-profiles-daemon.enable = false;

  # Firmware updates via fwupd (Dell XPS is well supported)
  services.fwupd.enable = true;

  # Touchscreen support (if present)
  services.libinput.enable = true;

  # LUKS configuration is handled by disko (modules/disko/xps9320.nix)
  # Disko sets allowDiscards and bypassWorkqueues automatically

  # Hibernate support (auto-generated by Forge installer)
  # These values will be updated after installation
  boot.resumeDevice = "/dev/mapper/cryptroot";
  # boot.kernelParams = [ "resume_offset=XXXXX" ];  # Set after install
  zramSwap.enable = lib.mkForce false;
}
