# Hardware configuration for Dell XPS 9320
# Generated by nixos-generate-config, manually enhanced for XPS-specific hardware
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Kernel modules available in initrd for hardware detection
  boot.initrd.availableKernelModules = [
    "xhci_pci"      # USB 3.x controller
    "thunderbolt"   # Thunderbolt 4 support
    "vmd"           # Intel Volume Management Device (NVMe)
    "nvme"          # NVMe storage
    "usb_storage"   # USB mass storage
    "sd_mod"        # SCSI disk support
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Thunderbolt 4 support (XPS 9320 has 2x TB4 ports)
  services.hardware.bolt.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
